auto: Checking if command is valid.

diff --git a/plugins/auto/burst b/plugins/auto/burst
--- a/plugins/auto/burst
+++ b/plugins/auto/burst
@@ -3,9 +3,14 @@
 
 # Autoload burst command
 local top=/projects/pd/pj00311_burst/users/todyam01/tools-dev
-if ! (hash burst &>/dev/null); then
+cmd=burst
+if ! (hash $cmd &>/dev/null); then
 	module load $top/modulefile
 fi
-unfunction burst
-burst $@
+if (hash $cmd &>/dev/null); then
+	unfunction $cmd
+	$cmd $@
+else
+	echo "ERROR: $cmd not found" 1>&2
+fi
 
diff --git a/plugins/auto/pdf b/plugins/auto/pdf
--- a/plugins/auto/pdf
+++ b/plugins/auto/pdf
@@ -1,10 +1,15 @@
 
 # vi: ft=zsh
 
-if ! (hash acroread &>/dev/null); then
+cmd=acroread
+if ! (hash $cmd &>/dev/null); then
 	module load adobe/acrobat/8.1.3
 fi
-unfunction pdf
-alias pdf='acroread'
-acroread $@
+if (hash $cmd &>/dev/null); then
+	unfunction pdf
+	alias pdf=$cmd
+	$cmd $@
+else
+	echo "ERROR: $cmd not found" 1>&2
+fi
 
diff --git a/plugins/auto/vcover b/plugins/auto/vcover
--- a/plugins/auto/vcover
+++ b/plugins/auto/vcover
@@ -5,6 +5,10 @@ cmd=$0
 if ! (hash $cmd &>/dev/null); then
 	module load mentor/questasim/2019.1_1
 fi
-unfunction $cmd
-$cmd $@
+if (hash $cmd &>/dev/null); then
+	unfunction $cmd
+	$cmd $@
+else
+	echo "ERROR: $cmd not found" 1>&2
+fi
 
